---
title: "plots"
author: "jabir"
date: "2023-09-22"
output: html_document
---


```{r}
library(spotifyr)
library(tidyverse)
library(lubridate)
library(corrplot)
library(usethis)
library(ggthemes)
```


```{r}
# grabbing every variable for further use
top_five_all <- good_songs_df |>
  arrange(desc(track.popularity)) |>
  arrange(year) |>
  mutate(year = as.factor(year)) |>
  group_by(year) |>
  top_n(5,track.popularity)

good_songs_df |>
  ggplot(aes(x = year, y= tempo)) +
  geom_point()

top_five_all |>
  ggplot(aes(x = year, y = tempo)) +
  geom_point()

# the energy of the songs does go up half way through the 90s and 2000s but they do drop back down in the 2010s
top_five_all |>
  ggplot(aes(x = release_date, y = energy)) +
  geom_point() +
   theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1))

# the loudness seems to start to increase through out the 90s on into the 2000s 
top_five_all |>
  ggplot(aes(x = release_date, y = loudness)) +
  geom_point() +
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust = 1))

combined_df |>
  ggplot(aes(x = release_date, y = loudness)) +
  geom_point() +
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust = 1))

# this also seems to increase even though any song can be danced to, also take note that there are less songs as the years increase
top_five_all |>
  ggplot(aes(x = release_date, y = danceability)) +
  geom_point() +
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust = 1))

good_songs_df |>
  ggplot(aes(x = release_date, y = danceability)) +
  geom_point() +
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust = 1))

```


```{r}
# Start making some plots with ggplot2 and explore possible relationships between the year of the song and any other variable that we might have in the dataset that you think may be related in some way. 
# Also maybe look at popularity and audio information 

ggplot2::ggplot(songs_df, ggplot2::aes(track.album.release_date, track.popularity)) + 
  ggplot2::geom_point()

good_songs_df |>
  ggplot(aes(x = track.popularity, y = year)) +
  geom_point()

top_songs_df <- good_songs_df |>
  select(track.name,track.popularity,year) |>
  arrange(desc(track.popularity)) |>
  arrange(year) |>
  mutate(year = as.factor(year)) |>
  group_by(year) |>
  top_n(5,track.popularity)

 most_pop_song_each_year <- good_songs_df |>
  select(track.name,track.popularity,year) |>
  arrange(desc(track.popularity)) |>
  arrange(year) |>
  mutate(year = as.factor(year)) |>
  group_by(year) |>
  top_n(1,track.popularity)
```


```{r}
top_songs_df |>
  ggplot(aes(x = year, y = track.popularity)) +
  geom_point() +
  labs(
    title = "Top 3-5 songs each year",
    y = "popularity"
  )

top_songs_df |>
  ggplot(aes(x = track.name, y = track.popularity,color = year)) +
  geom_point() +
  facet_wrap(vars(year))

good_songs_df |>
  ggplot(aes(x = year, y = track.popularity)) +
  geom_point() +
  labs(title = "Every song in each year",
       subtitle = "An overall scale of each year",
       x = "year",
       y = "popularity") +
   theme(axis.text.x = element_text(angle = 60, hjust = 1)) +
  ggthemes::theme_solarized()

top_songs_df |>
  ggplot(aes(x = track.name, y = track.popularity, fill = year)) +
  geom_bar(stat = "identity") +
  theme(axis.text.x = element_text(angle = 60, hjust = 1))

most_pop_song_each_year |>
  ggplot(aes(x = year, y = track.popularity)) +
  geom_point(color = "orange") +
  theme(axis.text.x = element_text(angle = 40,hjust = 1)) +
  labs(title = "Number one most popular song in each year",
       subtitle = "From 1978-2010",
       x = "Year",
       y = "popularity") +
 theme(panel.background = element_rect(fill = "black"),
        panel.grid.major = element_line(color = "black"),
        panel.grid.minor = element_line(color = "black"))
```

very unpopular songs having low ratings in popularity this playlist is filled with ear stredding ear bleeding horrible covers of songs

```{r}
trash_songs |>
  ggplot(aes(x = track.name, y = track.popularity)) +
  geom_point()

trash_songs |>
  ggplot(aes(x = track.name, y = track.popularity)) +
  geom_bar(stat = "identity")

trash_songs |>
  ggplot(aes(x = track.name, y = track.popularity)) +
  geom_boxplot()
```

running t test between the popular songs and the unpopular songs

```{r}
t.test(trash_songs$track.popularity,top_songs_df$track.popularity)
```


```{r}


all_songs_df |>
  ggplot(aes(x = song_group, y = track.popularity)) +
  geom_violin()

ggplot(data = all_songs_df, aes(x = song_group, y = danceability)) +
  geom_violin()


```

getting audio data from trash playlist

```{r}
all_songs_df |>
  ggplot(aes(x = song_group, y = danceability)) +
  geom_violin()

all_songs_df |>
  ggplot(aes(x = song_group, y = tempo)) +
  geom_violin()

all_songs_df |>
  ggplot(aes(x = song_group, y = liveness)) +
  geom_violin()

all_songs_df |>
  ggplot(aes(x = song_group, y = instrumentalness)) +
  geom_violin()

all_songs_df |>
  ggplot(aes(x = song_group, y = energy)) +
  geom_violin()

all_songs_df |>
  ggplot(aes(x = song_group, y = loudness)) +
  geom_violin()

all_songs_df |>
  ggplot(aes(x = song_group, y = acousticness)) +
  geom_violin()

all_songs_df |>
  ggplot(aes(x = song_group, y = key)) +
  geom_violin()

## Now you can clean up trash_songs_df and make plots from it

table(all_songs_df$song_group, all_songs_df$key)

```
