---
title: "Spotify Set up data"
output: html_notebook
---


```{r}
library(spotifyr)
library(tidyverse)
library(lubridate)
library(corrplot)
library(usethis)
library(ggthemes)

dir.create("data", showWarnings = FALSE)
```

```{r}
id <- "edcc2c4666f64421bf98439ad7daa85f"
secret <- "40de60ef43ca4831a5344c588a008fb4"

Sys.setenv(SPOTIFY_CLIENT_ID = id)
Sys.setenv(SPOTIFY_CLIENT_SECRET = secret)
access_token <- get_spotify_access_token()
```

## Set up hit songs data 

```{r}
playlists <- c(
  "1978" = "3mt2ysylQQ2cccDPyGfKID",
  "1979" = "6bHjBCFN8Lqj0K54RWFci8", 
  "1980" = "7DCh6mOvaEGMVph25k7hyN", 
  "1981" = "5wbHH4DqF4AVuGmjXI8kcW",
  "1982" = "1bk6tO6d5oes6n0vhACi5x",
  "1983" = "7GN1ulgzXBWpn5VADARkNd",
  "1984" = "10QxRag5DoKSR0iOwZ48Lt",
  "1985" = "7fGtXiE8qbQzqEisHw5CLS",
  "1986" = "4rhgAIno9OiopUzNhOZDbc",
  "1987" = "3fniVM8pbMq8jcR23aVIY8",
  "1988" = "1LCUqaG3ZbFnpJweV1lrj1",
  "1989" = "5ZjZbTHc6JBVu921hwc6v2",
  "1991" = "61FusglQju0yXpz3v7nYd5",
  "1992" = "0p6VwHqAZNV9xw5HuIKHJd",
  "1993" = "35wZqszdyXNFCAztyLWlgT",
  "1995" = "5zYgmmRp9ozLstVry1JLbw",
  "1996" = "0YKbjLgCPsp7K3k2JH4NZw", 
  "1997" = "6NewzRggzRDBBPowRuXBor", 
  "1998" = "62FCnGM83VWvtv6zAlMgTd", 
  "1999" = "0pnzsH8zKvnymNKOfPrT1P",
  "2000s" = "4cMLyIDCh4X90wgyEwYneN",
  "2010" = "5naqjby3xICvJte3QMvHcs"
  )

```

```{r}
good_songs <- lapply(playlists, get_playlist_tracks)

good_songs_df <- dplyr::bind_rows(good_songs, .id = "year") %>%
  readr::write_tsv(file.path("data","hit_songs_over_decades.tsv"))
```

Now get the audio information for all of those tracks.

```{r}
# We need to send these in batches so we don't reach the request limits
tracks_list <- split(good_songs_df$track.id, ceiling(seq_along(good_songs_df$track.id)/100))
# This loops through and requests info on the tracks in chunks
track_audio_features <- lapply(tracks_list, function(chunk) {
  tracks <- paste0(chunk, collapse = ",")
  Sys.sleep(90)
  return(get_track_audio_features(tracks))
})
```

```{r}
# Collapse back down to a data frame
track_audio_df <- bind_rows(track_audio_features)

# Get rid of songs that don't have audio info
track_audio_df <- track_audio_df |>
   filter(!is.na(tempo))
```

Put all the song info together in one data frame 

```{r}
# Combine audio info with song info from above 
track_audio_df <- track_audio_df |>
  rename(track.id = id) %>% 
  dplyr::distinct()

good_songs_df <- dplyr::inner_join(track_audio_df, good_songs_df, by = "track.id")
```

Let's extract the actual song release year from the variable `track.album.release_date`
The dates look like this "1978-04-04"

```{r}
good_songs_df <- good_songs_df |> 
 dplyr::mutate(release_date = stringr::word(track.album.release_date, sep = "-", 1)) |> 
 dplyr::filter(!is.na(release_date))
```

Collect all the unpopular songs playlist information 

```{r}
worst_song_playlist <- c("47LqfQL7pHzfCFl8wOjPn7","1te9h48c8YEPx5LiryMg5l","1FASvwq3uL0GEbEP8yMoBu")

trash_songs <- lapply(worst_song_playlist, get_playlist_tracks)

trash_songs <- bind_rows(trash_songs, .id = "playlist_id")

readr::write_rds(trash_songs , file.path("data", "trash_songs.RDS"))
```

```{r}
# We need to send these in batches so we don't reach the request limits
trash_tracks_list <- split(trash_songs$track.id, ceiling(seq_along(trash_songs$track.id)/100))
# This loops through and requests info on the tracks in chunks
trash_track_audio <- lapply(trash_tracks_list, function(chunk) {
  tracks <- paste0(chunk, collapse = ",")
  Sys.sleep(90)
  return(get_track_audio_features(tracks))
})

# Make into a dataframe 
trash_track_audio <- trash_track_audio %>% 
  dplyr::bind_rows() %>% 
  readr::write_tsv(file.path("data","trash_audio_info.tsv"))

trash_track_audio <- trash_track_audio |>
  rename(track.id = id) %>% 
  dplyr::distinct()
```


```{r}
# Put audio info together with original trash song info
trash_songs_df <- dplyr::inner_join(trash_songs, trash_track_audio, by = "track.id")
```

## Put all songs in one data frame and save that to an RDS

```{r}
saveRDS(trash_songs_df,file.path("data","trash_songs_df.rds"))

saveRDS(good_songs_df,file.path("data","good_songs_df.rds"))

all_songs_df <- bind_rows(list(unpopular = trash_songs_df, popular = good_songs_df), 
                          .id= "song_group")

readr::write_rds(all_songs_df , file.path("data", "all_songs.RDS"))
```


```{r}
# Print out session info here
sessionInfo()
```
